<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <!-- Aquí bloqueamos el error de DevExpress -->
    <RestoreSources>https://api.nuget.org/v3/index.json</RestoreSources>
  </PropertyGroup>

  <ItemGroup>
    <!-- Y aquí instalamos los paquetes a la fuerza -->
    <PackageReference Include="MySqlConnector" Version="2.6.2" />
    <PackageReference Include="BCrypt.Net-Next" Version="4.2.0" />
  </ItemGroup>

</Project>